### ISSUE TITLE
Add filter to take first n element of a sequence

### ISSUE THREAD

**Issue by markokocic** [clarete/templatel#11] opened 2021-03-17 10:37 UTC
I can get `first` or `last` element of a sequence, but not `take 5`.

I'd like to be able to do 
``` jinja
{% for post in posts|take(5) %}
  {{post.description}}
{% endfor %}
```
That should return up to `5` posts if there are 5 or more, otherwise as much as there are.

**Comment by markokocic** [comment] 2021-03-17 12:05
I actually tried implementing this filter myself, but got stuck. I'm probably missing something basic.

I created the following function in `templatel.el`

``` elisp
(defun templatel-filters-take (s n)
  "Take n elements of sequence S."
  (seq-take s n))
```
and added it to the list of `rt/filters` like this `("take" . templatel-filters-take)`

However, I couldn't find a way to actually use it in my template:
``` jinja
{% for post in posts|take(4) %}
```
gives `Wrong type argument: listp, 4`

``` jinja
{% for posts in take(posts, 4) %}
```
gives `Wrong type argument: number-or-marker-p, ......` and then displays `post` lisp structure in console output.

What am I missing here?

**Comment by clarete** [comment] 2021-03-17 13:40
Hi @markokocic thanks thinking of such cool and useful addition.  I think your implementation is pretty much what I would have done myself.  I think the issue is in how the for loop gets compiled.  I think it doesn't play gracefully with filter application.  When I tried the changes you suggested locally, I wrote the following little test:

```emacs-lisp
(ert-deftest render-expr-filter-take ()
  (should (equal "(1 2 3 4)"
                 (templatel-render-string
                  "{{ things | take(4) }}"
                  '(("things" . (1 2 3 4 5 6 7 8))))))
  (should (equal "1, 2, 3, 4, "
                 (templatel-render-string
                  "{% for i in things | take(4) %}{{ i }}, {% endfor %}"
                  '(("things" . (1 2 3 4 5 6 7 8)))))))
```

The first assertion works but the second fails with something that at first glance looks like an error in the assignment of the `i` variable in the loop:

```
Test render-expr-filter-take condition:
    (ert-test-failed
     ((should
       (equal "1, 2, 3, 4, "
              (templatel-render-string "{% for i in things | take(4) %}{{ i }}, {% endfor %}" ...)))
      :form
      (equal "1, 2, 3, 4, " "(1 2 3 4), 4, ")
      :value nil :explanation
      (arrays-of-different-length 12 14 "1, 2, 3, 4, " "(1 2 3 4), 4, " first-mismatch-at 0)))
   FAILED  1/1  render-expr-filter-take (0.016052 sec)
```

I'll take a deeper look at it! Thanks for finding this bug! 🙇🏾

**Comment by clarete** [comment] 2021-03-17 13:42
Also, I pushed a few changes related to filters recently. They shouldn't impact your change in any way, but you might have to rebase your branch 😭

**Comment by clarete** [comment] 2021-03-18 23:37
Hi @markokocic I believe I fixed the issue that was preventing you from seeing your filter working.  I didn't close this issue because maybe you were planning on opening a pull request to add the `take`  filter yourself 😄

**Closed** 2021-03-19 22:22 UTC
Labels: bug, enhancement
